// STATE CONSTANTS
export const SIGN_USER = 'SIGN_USER';
export const SIGN_USER_REQUEST = 'SIGN_USER_REQUEST';
// GETTER CONSTANTS
export const GET_SIGN_USER = 'GET_SIGN_USER';
export const GET_SIGN_USER_REQUEST = 'GET_SIGN_USER_REQUEST';
// MUTATION CONSTANTS
export const SET_SIGN_USER = 'SET_SIGN_USER';
export const SET_SIGN_USER_REQUEST = 'SET_SIGN_USER_REQUEST';
// ACTION CONSTATS
export const FETCH_SIGN_USER = 'FETCH_SIGN_USER';
export const FETCH_SIGN_USER_REQUEST = 'FETCH_SIGN_USER_REQUEST';
