// STATE CONSTANTS
export const SIGN_USER = 'SIGN_USER';
// GETTER CONSTANTS
export const GET_SIGN_USER = 'GET_SIGN_USER';
// MUTATION CONSTANTS
export const SET_SIGN_USER = 'SET_SIGN_USER';
// ACTION CONSTATS
export const FETCH_SIGN_USER = 'FETCH_SIGN_USER';
